import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import api from '../../utils/api'
import { FileText, Search, ExternalLink } from 'lucide-react'

export default function AdminReports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  useEffect(() => {
    api.get('/admin/reports/all').then(r => setReports(r.data)).finally(() => setLoading(false))
  }, [])

  const filtered = search
    ? reports.filter(r =>
        r.reportId?.toLowerCase().includes(search.toLowerCase()) ||
        r.patient?.name?.toLowerCase().includes(search.toLowerCase()))
    : reports

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">All Reports</h1>
        <p className="text-gray-500 text-sm mt-1">{reports.length} reports generated</p>
      </div>

      <div className="relative">
        <Search size={15} className="absolute left-3 top-2.5 text-gray-400" />
        <input className="input pl-8" placeholder="Search by report ID or patient name…"
          value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      {loading ? (
        <div className="space-y-3">{[...Array(4)].map((_, i) => <div key={i} className="h-16 bg-gray-100 rounded-xl animate-pulse" />)}</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <FileText size={48} className="mx-auto mb-3 opacity-30" />
          <p>No reports found</p>
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Report ID</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Patient</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Tests</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Generated By</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Date</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(r => (
                <tr key={r._id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-5 py-3 font-mono text-sm font-bold text-lab">{r.reportId}</td>
                  <td className="px-5 py-3">
                    <div className="text-sm font-medium text-gray-900">{r.patient?.name}</div>
                    <div className="text-xs text-gray-400">{r.patient?.email}</div>
                  </td>
                  <td className="px-5 py-3 text-xs text-gray-500 max-w-40 truncate">
                    {r.booking?.tests?.map(t => t.name).join(', ')}
                  </td>
                  <td className="px-5 py-3 text-sm text-gray-600">{r.generatedBy?.name || '—'}</td>
                  <td className="px-5 py-3 text-xs text-gray-400">
                    {new Date(r.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}
                  </td>
                  <td className="px-5 py-3">
                    <a href={`/api/reports/${r._id}/pdf`} target="_blank" rel="noreferrer"
                      className="flex items-center gap-1 text-xs text-lab hover:underline font-medium">
                      <ExternalLink size={12} /> View PDF
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}